app:
  node_env: NODE_ENV
  name: APP_NAME
  port: APP_PORT
  prefix: APP_PREFIX
  jwt_access_token_secret: JWT_ACCESS_TOKEN_SECRET
  jwt_access_token_expiration_time: JWT_ACCESS_TOKEN_EXPIRATION_TIME
  jwt_refresh_token_secret: JWT_REFRESH_TOKEN_SECRET
  jwt_refresh_token_expiration_time: JWT_REFRESH_TOKEN_EXPIRATION_TIME

redis:
  host: REDIS_HOST
  port: REDIS_PORT

kafka:
  brokers: KAFKA_BROKERS

sentry_dns: SENTRY_DNS

master_mssql:
  type: SQL_TYPE
  host: SQL_HOST
  port: SQL_PORT
  username: SQL_USERNAME
  password: SQL_PASSWORD

mail:
  host: MAIL_HOST
  port: MAIL_PORT
  account: MAIL_ACCOUNT
  password: MAIL_PASSWORD
  from: MAIL_FROM
  service: MAIL_SERVICE
  enable: MAIL_ENABLE

aws_config:
  upload_path: UPLOAD_PATH
  aws_access_key_id: AWS_ACCESS_KEY_ID
  aws_secret_access_key: AWS_SECRET_ACCESS_KEY
  aws_bucket_name: AWS_BUCKET_NAME
  aws_region: AWS_REGION
  domain: DOMAIN
  upload_limit: UPLOAD_LIMIT

mongodb:
  uri: MONGO_URI

facebook:
  graph_api: FACEBOOK_GRAPH_API

google:
  base_api: GOOGLE_BASE_API

server: 
  web_url: WEB_URL

sign_up_expiration_time: SIGN_UP_EXPIRATION_TIME
forgot_password_expiration_time: FORGOT_PASSWORD_EXPIRATION_TIME