app:
  node_env: NODE_ENV
  name: APP_NAME
  port: APP_PORT
  prefix: APP_PREFIX
  jwt_access_token_secret: JWT_ACCESS_TOKEN_SECRET
  jwt_access_token_expiration_time: JWT_ACCESS_TOKEN_EXPIRATION_TIME
  jwt_refresh_token_secret: JWT_REFRESH_TOKEN_SECRET
  jwt_refresh_token_expiration_time: JWT_REFRESH_TOKEN_EXPIRATION_TIME

redis:
  host: REDIS_HOST
  port: REDIS_PORT

kafka:
  brokers: KAFKA_BROKERS

sentry_dns: SENTRY_DNS

mail:
  account: MAIL_ACCOUNT
  password: MAIL_PASSWORD
  from: MAIL_FROM
  service: MAIL_SERVICE
  domain: MAIL_DOMAIN
  enable: MAIL_ENABLE

aws_config:
  upload_path: UPLOAD_PATH
  aws_access_key_id: AWS_ACCESS_KEY_ID
  aws_secret_access_key: AWS_SECRET_ACCESS_KEY
  aws_bucket_name: AWS_BUCKET_NAME
  aws_region: AWS_REGION
  domain: DOMAIN
  upload_limit: UPLOAD_LIMIT

mongodb:
  uri: MONGO_URI

facebook:
  graph_api: FACEBOOK_GRAPH_API

google:
  base_api: GOOGLE_BASE_API

paypal:
  mode: PAYPAL_MODE
  client_id: PAYPAL_CLIENT_ID
  client_secret: PAYPAL_CLIENT_SECRET
  return_url: PAYPAL_RETURN_URL
  cancel_url: PAYPAL_CANCEL_URL
  base_url: BASE_URL